apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: tdl
  labels:
    app: todolist
    tier: frontend
spec:
  type: NodePort
  selector:
    app: todolist
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: "angular-service"
