apiVersion: v1
kind: Service
metadata:
  name: todolist-api
  namespace: tdl
  labels:
    app: todolist-api
    tier: backend
spec:
  type: NodePort
  selector:
    app: api
    tier: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
      name: "api-service"
