apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: tdl
  labels:
    app: grafana
    tier: observability
spec:
  type: NodePort
  selector:
    app: grafana
    tier: observability
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30083
      name: "grafana-service"
