apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: tdl
  labels:
    app: mysql
    tier: db
spec:
  selector:
    app: mysql
    tier: db
  ports:
    - port: 3306
      targetPort: 3306
      name: "mysql-service"
