apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: tdl
  labels:
    app: phpmyadmin
    tier: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      tier: observability
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
        tier: observability
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: PMA_HOST
            value: db
          - name: PMA_PORT
            value: "3306"
