apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: tdl
  labels:
    app: phpmyadmin
    tier: observability
spec:
  type: NodePort
  selector:
    app: phpmyadmin
    tier: observability
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30082
      name: "phpmyadmin-service"
