apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: tdl
  labels:
    app: redis
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: db
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
