apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: tdl
  labels:
    app: redis
    tier: db
spec:
  selector:
    app: redis
    tier: db
  ports:
    - port: 6379
      targetPort: 6379
      name: "redis-service"
