apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: tdl
  labels:
    app: redisinsight
    tier: observability
spec:
  type: NodePort
  selector:
    app: redisinsight
    tier: observability
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30081
      name: "result-service"
